import type { CollectionConfig } from "payload";

export const BlogPosts: CollectionConfig = {
  slug: "blog-posts",
  admin: {
    useAsTitle: "title",
    defaultColumns: ["title", "category", "status", "publishedDate"],
  },
  versions: {
    drafts: true,
  },
  fields: [
    {
      name: "title",
      type: "text",
      required: true,
    },
    {
      name: "slug",
      type: "text",
      required: true,
      unique: true,
      index: true,
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "excerpt",
      type: "textarea",
      maxLength: 300,
    },
    {
      name: "featuredImage",
      type: "upload",
      relationTo: "media",
    },
    {
      name: "content",
      type: "richText",
      required: true,
    },
    {
      name: "category",
      type: "select",
      required: true,
      options: [
        { label: "Wedding", value: "wedding" },
        { label: "Events", value: "events" },
        { label: "Photo Booth", value: "photo-booth" },
        { label: "Content Creation", value: "content-creation" },
      ],
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "tags",
      type: "array",
      fields: [
        {
          name: "tag",
          type: "text",
        },
      ],
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "author",
      type: "text",
      defaultValue: "Gigi",
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "publishedDate",
      type: "date",
      admin: {
        position: "sidebar",
        date: {
          pickerAppearance: "dayOnly",
        },
      },
    },
    {
      name: "aiGenerated",
      type: "checkbox",
      defaultValue: false,
      admin: {
        position: "sidebar",
        description: "Was this post generated by AI?",
      },
    },
    {
      name: "aiPrompt",
      type: "textarea",
      admin: {
        position: "sidebar",
        description: "The prompt used to generate this post",
        condition: (data) => data?.aiGenerated,
      },
    },
  ],
};
