import type { CollectionConfig } from "payload";

export const BlogPosts: CollectionConfig = {
  slug: "blog-posts",
  admin: {
    useAsTitle: "title",
    defaultColumns: ["title", "category", "status", "publishedDate"],
    group: "Website",
    description: "Blog articles that help attract visitors from Google. HOW TO USE: 1) Click 'Create New'. 2) Write your title, choose a category, and add content using the rich text editor. 3) Upload a featured image (click the image field, then upload or choose from Media). 4) Write a short excerpt for Google search results. 5) Set the publish date and click 'Publish'. TIP: Aim for 1-2 posts per week about Dallas weddings, events, and photo tips to boost your Google ranking.",
    components: {
      beforeList: ["@/components/admin/InstructionsBox#InstructionsBox"],
    },
  },
  versions: {
    drafts: true,
  },
  fields: [
    {
      name: "title",
      type: "text",
      required: true,
      admin: { description: "The headline of your blog post — make it engaging and descriptive" },
    },
    {
      name: "slug",
      type: "text",
      required: true,
      unique: true,
      index: true,
      admin: {
        position: "sidebar",
        description: "URL-friendly version of the title (e.g. 'my-wedding-tips'). Must be unique",
      },
    },
    {
      name: "excerpt",
      type: "textarea",
      maxLength: 300,
      admin: { description: "A short preview shown on the blog list page and in search results (max 300 characters)" },
    },
    {
      name: "featuredImage",
      type: "upload",
      relationTo: "media",
      admin: { components: { afterInput: ["@/components/admin/AIImageButton#AIImageButton"] }, description: "The main image shown at the top of the post and on the blog list" },
    },
    {
      name: "content",
      type: "richText",
      required: true,
      admin: { description: "The full blog post content — write your heart out!" },
    },
    {
      name: "category",
      type: "select",
      required: true,
      options: [
        { label: "Wedding", value: "wedding" },
        { label: "Events", value: "events" },
        { label: "Photo Booth", value: "photo-booth" },
        { label: "Content Creation", value: "content-creation" },
      ],
      admin: {
        position: "sidebar",
        description: "Which category does this post belong to?",
      },
    },
    {
      name: "tags",
      type: "array",
      fields: [
        {
          name: "tag",
          type: "text",
          admin: { description: "A keyword or topic tag (e.g. 'dallas', 'luxury', 'tips')" },
        },
      ],
      admin: {
        position: "sidebar",
        description: "Tags help visitors find related posts",
      },
    },
    {
      name: "author",
      type: "text",
      defaultValue: "Gigi",
      admin: {
        position: "sidebar",
        description: "Who wrote this post?",
      },
    },
    {
      name: "publishedDate",
      type: "date",
      admin: {
        position: "sidebar",
        date: {
          pickerAppearance: "dayOnly",
        },
        description: "When should this post appear as published?",
      },
    },
    {
      name: "aiGenerated",
      type: "checkbox",
      defaultValue: false,
      admin: {
        position: "sidebar",
        description: "Was this post generated by AI?",
      },
    },
    {
      name: "aiPrompt",
      type: "textarea",
      admin: {
        position: "sidebar",
        description: "The prompt used to generate this post",
        condition: (data) => data?.aiGenerated,
      },
    },
  ],
};
